# 2 시퀀스

코드에서 감을 잡았겟지만, 여기서 설명한 연산들은 텍스트, 리스트, 테이블에도 동일하게 적용된다.

텍스트, 리스트, 테이블을 합쳐서 '기차'라고 부른다. [중략]

일반적으로 FOR 명령어도 기차에 사용할 수 있다.

 -- 거츠, 미어텐즈, 펨버튼 "ABC Programmer's Handbook"

# 2.1 내장 시퀀스 개요

## 2.2 지능형 리스트와 제너레이터 표현식

- 컨테이너 시퀀스 : 서로 다른 자료형의 항목들을 담을 수 있는 list, tuple, collections.deque 형
- 균일 시퀀스 : 단 하나의 자료형만 담을 수 있는 str, bytes, bytearray, memoryview, array.array 형

- 가변 시퀀스 : list, bytearray, array.array, collections.deque, memoryview 형
- 불변 시퀀스 : tuple, str, bytes 형

### 2.2.1 지능형 리스트와 가독성

In [6]:
symbols = '$!@%'
codes = [ord(symbol) for symbol in symbols]
codes

[36, 33, 64, 37]

In [1]:
x = 'my precious'
dummy = [x for x in 'ABC']
x

'my precious'

In [3]:
x = 'ABC'
dummy = [ord(x) for x in x]
x

'ABC'

In [4]:
dummy

[65, 66, 67]

### 2.2.2 지능형 리스트와 map()/filter() 비교

In [2]:
symbols = '$!@%'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 33]
beyond_ascii

[36, 64, 37]

In [3]:
beyond_ascii = list(filter(lambda c: c > 33, map(ord, symbols)))
beyond_ascii

[36, 64, 37]

### 2.2.3. 데카르트 곱

In [41]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [45]:
for color in colors:
    for size in sizes:
        print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [46]:
tshirts = [(color, size) for size in sizes
                         for color in colors]
tshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

### 2.2.4 제너레이터 표현식

In [2]:
symbols = '!@#$'
tuple(ord(symbol) for symbol in symbols)

(33, 64, 35, 36)

In [3]:
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [33, 64, 35, 36])

In [4]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirts in ('%s %s' % (c, s) for c in colors for s in sizes):
    print(tshirts)

black S
black M
black L
white S
white M
white L


# 2.3 튜플은 단순한 불변 리스트가 아니다

### 2.3.1 레코드로서의 튜플

In [5]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('EXP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)


BRA/CE342567
EXP/XDA205856
USA/31195855


In [6]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
EXP


### 2.3.2 튜플 언패킹

In [7]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates  # 튜플 언패킹
print(latitude, longitude)

33.9425 -118.408056


In [8]:
divmod(20, 8)

(2, 4)

In [10]:
t = (20, 8)
divmod(*t)

(2, 4)

In [11]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [12]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [14]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [16]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [17]:
a, *body, c, d = range(5)

In [18]:
a, body, c, d

(0, [1, 2], 3, 4)

In [19]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

### 2.3.3 내포된 튜플 언패킹

In [20]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


### 2.3.4 namedtuple

In [23]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [24]:
tokyo.population

36.933

In [25]:
tokyo.coordinates

(35.689722, 139.691667)

In [26]:
tokyo[1]

'JP'

In [27]:
City._fields

('name', 'country', 'population', 'coordinates')

In [28]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613889, long=77.208889)}

In [29]:
for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


### 2.3.5 불변 리스트로서의 튜플

튜플은 추가하거나 삭제하는 기능, __reversed__() 메서드를 제외하면 리스트가 제공하는 메서드를 모두 지원함.

# 2.4 슬라이싱

In [6]:
seq = 'bicycle'
seq[1:5:2]

'iy'

In [12]:
invoice = """
0.....6.................................40...........52...55..........
1909  Pimoroni Pibrella                        $17.50        3      $52.50
1489  6mm Tactile Switch x20                    $4.95        2       $9.90
1510  Panavise Jr. - PV-201                    $28.00        1      $28.00
1601  PiTFT mini Kit 320x240                   $34.95        1      $34.95
"""

In [21]:
SKU = slice(6, 40)
line_items = invoice.split('\n')[2:]

In [22]:
line_items

['1909  Pimoroni Pibrella                        $17.50        3      $52.50',
 '1489  6mm Tactile Switch x20                    $4.95        2       $9.90',
 '1510  Panavise Jr. - PV-201                    $28.00        1      $28.00',
 '1601  PiTFT mini Kit 320x240                   $34.95        1      $34.95',
 '']

In [23]:
for item in line_items:
    print(item[SKU])

Pimoroni Pibrella                 
6mm Tactile Switch x20            
Panavise Jr. - PV-201             
PiTFT mini Kit 320x240            



In [27]:
import numpy as np
a = np.arange(12)
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [30]:
a[2, ...]

array([ 8,  9, 10, 11])

In [38]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [40]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

### 질문

In [32]:
my_list = list(range(10))
my_list[:None] == my_list[:]

True