# 2.2 지능형 리스트와 제너레이터 표현식

In [7]:
symbols = '$!@%'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
codes

[36, 33, 64, 37]

In [6]:
symbols = '$!@%'
codes = [ord(symbol) for symbol in symbols]
codes

[36, 33, 64, 37]

In [9]:
x = 'my precious'
dummy = [x for x in 'ABC']
x

'my precious'

In [10]:
x = 'ABC'
dummy = [ord(x) for x in x]
x

'ABC'

In [11]:
dummy

[65, 66, 67]

### 2.2.2 지능형 리스트와 map()/filter() 비교

In [2]:
symbols = '$!@%'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 33]
beyond_ascii

[36, 64, 37]

In [3]:
beyond_ascii = list(filter(lambda c: c > 33, map(ord, symbols)))
beyond_ascii

[36, 64, 37]

### 2.2.3. 데카르트 곱

In [41]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [45]:
for color in colors:
    for size in sizes:
        print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [46]:
tshirts = [(color, size) for size in sizes
                         for color in colors]
tshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

### 2.2.4 제너레이터 표현식

# 2.4 슬라이싱

In [6]:
seq = 'bicycle'
seq[1:5:2]

'iy'

In [12]:
invoice = """
0.....6.................................40...........52...55..........
1909  Pimoroni Pibrella                        $17.50        3      $52.50
1489  6mm Tactile Switch x20                    $4.95        2       $9.90
1510  Panavise Jr. - PV-201                    $28.00        1      $28.00
1601  PiTFT mini Kit 320x240                   $34.95        1      $34.95
"""

In [21]:
SKU = slice(6, 40)
line_items = invoice.split('\n')[2:]

In [22]:
line_items

['1909  Pimoroni Pibrella                        $17.50        3      $52.50',
 '1489  6mm Tactile Switch x20                    $4.95        2       $9.90',
 '1510  Panavise Jr. - PV-201                    $28.00        1      $28.00',
 '1601  PiTFT mini Kit 320x240                   $34.95        1      $34.95',
 '']

In [23]:
for item in line_items:
    print(item[SKU])

Pimoroni Pibrella                 
6mm Tactile Switch x20            
Panavise Jr. - PV-201             
PiTFT mini Kit 320x240            



In [25]:
pip install numpy

     |████████████████████████████████| 10.7 MB 2.7 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for numpy: filename=numpy-1.23.3-cp39-cp39-macosx_12_0_arm64.whl size=5231589 sha256=2f1bfcc97e1470293774fdbc36a0a1e64238a23e468d37c0d4a4f173eb4edd00
  Stored in directory: /Users/kyeongchanlee/Library/Caches/pip/wheels/bd/0b/8d/4066141d9040b64f6f899d725177a16bf9ee55dc35a1adba23
Successfully built numpy
You should consider upgrading via the '/Users/kyeongchanlee/.pyenv/versions/3.9.1/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [27]:
import numpy as np
a = np.arange(12)
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [30]:
a[2, ...]

array([ 8,  9, 10, 11])

In [38]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [40]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]