## 2.5 시퀀스에 덧셈과 곱셈 연산자 ㅇ사용하기

In [2]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:

5 * 'abcd'

'abcdabcdabcdabcdabcd'

2.5.1 리스트의 리스트 만들기

In [4]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [6]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [7]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [8]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [9]:
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)

In [10]:
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [11]:
board[2][0] = 'X'
board

[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

## 2.6 시퀀스의 복합할당

In [13]:
l = [1, 2, 3]
id(l)

4569930944

In [14]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [15]:
id(l)

4569930944

In [16]:
t = (1, 2, 3)
id(t)

4642024192

In [17]:
t *= 2
id(t)

4652125728

2.6.1 += 복합 할당 퀴즈

In [19]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [20]:
import dis
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


## 2.7 list.sort()와 sorted() 내장 함수

In [22]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [23]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [24]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [25]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [26]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [27]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [28]:
fruits.sort()

In [30]:

fruits

['apple', 'banana', 'grape', 'raspberry']

## 2.8 정렬된 시퀀스를 bisect로 관리하기

2.8.1 bisect()로 검색하기

In [33]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        print(ROW_FMT.format(needle, position, offset))

if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect

    print('DEMO:', bisect_fn.__name__)
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)

DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [34]:
def grade(score, breakpoint=[60, 70, 80, 90], grades='FCDBA'):
    i = bisect.bisect(breakpoint, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'D', 'D', 'B', 'A', 'A']

2.8.2 bisect.insort()로 삽입하기

In [35]:
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d -> ' % new_item, my_list)

10 ->  [10]
 0 ->  [0, 10]
 6 ->  [0, 6, 10]
 8 ->  [0, 6, 8, 10]
 7 ->  [0, 6, 7, 8, 10]
 2 ->  [0, 2, 6, 7, 8, 10]
10 ->  [0, 2, 6, 7, 8, 10, 10]


## 2.9 리스트가 답이 아닐 때

2.9.1 배열

In [36]:
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.5963321947530882

In [37]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]

0.5963321947530882

In [38]:
floats2 == floats

True

2.9.2 메모리 뷰

In [39]:
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [40]:
memv[0]

-2

In [41]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [42]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

2.9.3 NumPy와 SciPy

In [43]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
type(a)

numpy.ndarray

In [45]:
a.shape

(12,)

In [46]:
a.shape = 3, 4

In [47]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a[2]

array([ 8,  9, 10, 11])

In [49]:
a[2, 1]

9

In [50]:
a[:, 1]

array([1, 5, 9])

In [51]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
floats = np.loadtxt('floats-10M-lines.txt')
floats[-3:]

In [ ]:
floats *= .5
floats[-3:]

In [ ]:
from time import perf_counter as perf_counter
t0 = pc(); floats /= 3; pc() - t0

In [53]:
np.save('floats-10M', floats)
floats2 = np.load('floats-10M.npy', 'r+')
floats2 *= 6
floats2[-3:]

memmap([3.23278983, 3.30542739, 3.57799317])

2.9.4 덱 및 기타 큐

In [63]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [65]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [66]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [68]:
dq.extendleft([10, 20 ,30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])