# 2.2 지능형 리스트와 제너레이터 표현식

## 2.2.1 지능형 리스트와 가독성

In [1]:
symbols = '@$#%@#'
codes = []

for symbol in symbols:
    codes.append(ord(symbol))
    
print(codes)

[64, 36, 35, 37, 64, 35]


In [2]:
symbols = '@$#%@#'
codes = [ ord(symbol) for symbol in symbols]
print(codes)

[64, 36, 35, 37, 64, 35]


In [3]:
x = 'ABC'
dummy = [ord(x) for x in x ]
print(x)
print(dummy)

ABC
[65, 66, 67]


In [4]:
symbols = '@$#%@#'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
print(beyond_ascii)

beyond_ascii = list(filter(lambda c:c>127, map(ord, symbols)))
print(beyond_ascii)

[]
[]


## 2.2.3 데카르트 곱

In [8]:
colors = ['black','white']
sizes = ['S','M','L']
tshirts = [(color,size) for color in colors for size in sizes ]
print(tshirts)

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]


In [9]:
for color in colors:
    for size in sizes:
        print((color,size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [11]:
tshirts = [(color, size) for size in sizes
                         for color in colors]
print(tshirts)

[('black', 'S'), ('white', 'S'), ('black', 'M'), ('white', 'M'), ('black', 'L'), ('white', 'L')]


## 2.2.4 제너레이터 표현식

In [12]:
symbols = '@$#%@#'
print(tuple(ord(symbol) for symbol in symbols))

(64, 36, 35, 37, 64, 35)


In [13]:
import array
print(array.array('I',((ord(symbol) for symbol in symbols)) ))

array('I', [64, 36, 35, 37, 64, 35])


In [14]:
colors = ['black','white']
sizes = ['S','M','L']

# 반복문을 통해 생성된 객체를 따로 사용하는 것이 아니므로 이 경우는 list comp. 보다 generator가 메모리적으로 더 효율적
for tshirts in ('%s %s'%(c,s) for c in colors for s in sizes):
    print(tshirts)

black S
black M
black L
white S
white M
white L


# 2.3 튜플은 단순한 불변 리스트가 아니다 

## 2.3.1 레코드로서의 튜플

In [18]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo',2003, 32450, 0.66, 8014)
traveler_ids =[('USA','31195855'),("BRA",'CE342567'),('ESP','XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' %passport)
    
for country, _ in traveler_ids:
    print(country)

BRA/CE342567
ESP/XDA205856
USA/31195855
USA
BRA
ESP


## 2.3.2 튜플 언패킹

In [19]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates

print(latitude)
print(longitude)

33.9425
-118.408056


In [22]:
print(divmod(20,8))
t = (20,8)
print(divmod(*t))

quotient, remainder = divmod(*t)
print(quotient, remainder)

(2, 4)
(2, 4)
2 4


In [23]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
print(filename)

idrsa.pub


In [27]:
a,b,*rest = range(5)
print(a,b,rest)

a,b,*rest = range(3)
print(a,b,rest)

a,b,*rest = range(2)
print(a,b,rest)

0 1 [2, 3, 4]
0 1 [2]
0 1 []


In [30]:
a,*body, c, d = range(5)
print(a, body, c, d)

*head , b, c, d = range(5)
print(head, b, c, d)

0 [1, 2] 3 4
[0, 1] 2 3 4


In [37]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

print('{:15} | {:^9} | {:^9}'.format('','lat.','long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitue, longitude) in metro_areas:
    if longitude <= 0 :
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |   33.9425 |  -99.1333
New York-Newark |   33.9425 |  -74.0204
São Paulo       |   33.9425 |  -46.6358


## 2.3.4 명명된 튜플

In [38]:
from collections import namedtuple
City = namedtuple('City','name country population coordinates')
tokyo = City('Tokyo','JP',36.933 , (35.689722,139.691667))
print(tokyo)
print(tokyo.population)
print(tokyo.coordinates)
print(tokyo[1])

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))
36.933
(35.689722, 139.691667)
JP


In [43]:
print(City._fields)
LatLong = namedtuple('LatLong','lat long')
delhi_data = ('Delhi NCR','In', 21.935, LatLong(28.613889,77.208889))
delhi = City._make(delhi_data) # City( ~~ ) 랑 City._make(~~) 랑 같은 역할인가보군
print(delhi._asdict())

for key , value in delhi._asdict().items():
    print(key + ':' , value)

('name', 'country', 'population', 'coordinates')
{'name': 'Delhi NCR', 'country': 'In', 'population': 21.935, 'coordinates': LatLong(lat=28.613889, long=77.208889)}
name: Delhi NCR
country: In
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


# 2.4 슬라이싱

## 2.4.1 슬라이스와 범위 지정시에 마지막 항목이 포함되지 않는 이유

In [46]:
l = [10,20,30,40,50,60]
print(l[:2])
print(l[2:])
print(l[:3])
print(l[3:])

[10, 20]
[30, 40, 50, 60]
[10, 20, 30]
[40, 50, 60]


## 2.4.2 슬라이스 객체

In [47]:
s = 'bicycle'
print(s[::3])
print(s[::-1])
print(s[::-2])

bye
elcycib
eccb


In [48]:
invoice = """
0.....6.................................40........52...55........
1909 Pimoroni PiBrella                      $17.50    3    $52.50
1489 6mm Tactile Switch x20                  $4.95    2    $9.90
1510 Panavise Jr. - PV-201                  $28.00    1    $28.00
1601 PiTFT Mini Kit 320x240                 $34.95    1    $34.95
"""

In [49]:
SKU = slice(0,6)
DESCRIPTION = slice(6,40)
UNIT_PRICE = slice(40,52)
QUANTITY = slice(52,55)
ITEM_TOTAL = slice(55,None)
line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

    $17.50   imoroni PiBrella                  
     $4.95   mm Tactile Switch x20             
    $28.00   anavise Jr. - PV-201              
    $34.95   iTFT Mini Kit 320x240             
 


## 2.4.4 슬라이스에 할당하기

In [50]:
l = list(range(10))
print(l)

# 4번째 index 는 그냥 사라지네
l[2:5] = [20,30]
print(l)

del l[5:7]
print(l)

l[3::2] = [11,22]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 5, 22, 9]


In [51]:
l[2:5] = 100

TypeError: can only assign an iterable

In [52]:
l[2:5] = [100]
print(l)

[0, 1, 100, 22, 9]


# 2.5 시퀀스에 덧셈과 곱셈 연산자 사용하기

## 2.5.1 리스트의 리스트 만들기

In [6]:
board = [['_'] *3 for i in range(3)]
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


In [7]:
board[1][2] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


In [8]:
weird_board = [ ['_'] * 3 ] * 3
print(weird_board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


In [10]:
weird_board[1][2] = '0'
print(weird_board)

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]


In [11]:
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)

In [12]:
board = []
for i in range(3):
    row = ['_']*3
    board.append(row)

In [13]:
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


In [14]:
board[2][0] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]


# 2.6 시퀀스의 복합 할당

In [16]:
l = [1,2,3]
print(id(l))

l*= 2
print(l)
print(id(l))

2225485698816
[1, 2, 3, 1, 2, 3]
2225485698816


In [17]:
t = (1,2,3)
print(id(t))

2225485768256


In [18]:
t*=2
print(t)
print(id(t))

(1, 2, 3, 1, 2, 3)
2225485734336


## 2.6.1 += 복합 할당 퀴즈

In [22]:
t = (1,2,[30,40])
t[2] += [50,60]

TypeError: 'tuple' object does not support item assignment

In [23]:
print(t)

(1, 2, [30, 40, 50, 60])


In [24]:
import dis

print(dis.dis('s[a]+=b'))

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE
None


# 2.7 list.sort() 와 sorted() 내장 함수

In [31]:
fruits = ['grape','raspberry','apple','banana']
print(sorted(fruits))
print(fruits)

['apple', 'banana', 'grape', 'raspberry']
['grape', 'raspberry', 'apple', 'banana']


In [32]:
print(sorted(fruits, reverse = True))
print(sorted(fruits, key = len))
print(sorted(fruits, key = len, reverse = True))

['raspberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'raspberry']
['raspberry', 'banana', 'grape', 'apple']


In [33]:
print(fruits)
fruits.sort()
print(fruits)

['grape', 'raspberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'raspberry']


# 2.8 정렬된 시퀀스를 bisect로 관리하기

- bisect 모듈은 bisect() 와 insort() 함수 제공
    - bisect() 는 이진 검색 알고리즘을 이용해서 시퀀스를 검색
    - insort() 는 정렬된 시퀀스 안에 항목을 삽입
- bisect 모듈은 리스트나 튜플뿐 아니라 시퀀스에도 적용된다. ( tuple 은 immutable 이므로 bisect.insort() 는 적용 안됨 ) 
<br><br>
- A needle in a haystack :  Something or someone that is difficult and nearly impossible to find.

## 2.8.1 bisect()로 검색하기

In [77]:
import bisect
import sys

HAYSTACK = [1,4,5,6,8,12,15,20,21,23,23,26,29,30]
NEEDLES  = [0,1,2,5,8,10,22,23,29,30,31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}' # #space bar = 4 

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK,needle)
        offset = position * '  |' # #space bar = 2
        print(ROW_FMT.format(needle,position,offset))
        
if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect
        
    print("DEMO: ", bisect_fn.__name__)
    print('haystack ->',' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)

DEMO:  bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [78]:
import bisect
import sys

HAYSTACK = [1,4,5,6,8,12,15,20,21,23,23,26,29,30]
NEEDLES  = [0,1,2,5,8,10,22,23,29,30,31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}' # #space bar = 4 

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK,needle)
        offset = position * '  |' # #space bar = 2
        print(ROW_FMT.format(needle,position,offset))
        
if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect_left
        
    print("DEMO: ", bisect_fn.__name__)
    print('haystack ->',' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)

DEMO:  bisect_left
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 12      |  |  |  |  |  |  |  |  |  |  |  |29
23 @  9      |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  4      |  |  |  |8 
 5 @  2      |  |5 
 2 @  1      |2 
 1 @  0    1 
 0 @  0    0 


In [168]:
# what if the list that we are interested in ( = haystack ) is sorted in descending order?
# And we have to keep the desecnding order at last
import bisect
import sys
import time
import copy

HAYSTACK = sorted(np.random.rand(100000).tolist(),reverse = True)
NEEDLES = sorted(np.random.rand(100000).tolist(),reverse = True)

def insort(HAYSTACK,NEEDLES):
    for needle in NEEDLES:
        bisect.insort(HAYSTACK,needle)
    return HAYSTACK

# 1 .sort()
since = time.time()
HAYSTACK1 = copy.deepcopy(HAYSTACK)
HAYSTACK1.sort()
HAYSTACK1 = insort(HAYSTACK1,NEEDLES)
HAYSTACK1.sort(reverse = True)
elapsed = time.time() - since
print("Case 1) use .sort() : " , elapsed)

# 2 sorted()
since = time.time()
HAYSTACK2 = copy.deepcopy(HAYSTACK)
HAYSTACK2 = sorted(HAYSTACK2)
HAYSTACK2 = insort(HAYSTACK2,NEEDLES)
HAYSTACK2 = sorted(HAYSTACK2,reverse = True)
elapsed = time.time() - since
print("Case 2) use sorted() : " , elapsed)

# 3 [::-1]
since = time.time()
HAYSTACK3 = copy.deepcopy(HAYSTACK)
HAYSTACK3 = HAYSTACK3[::-1]
HAYSTACK3 = insort(HAYSTACK3,NEEDLES)
HAYSTACK3 = HAYSTACK3[::-1]
elapsed = time.time() - since
print("Case 3) use [::-1] : " , elapsed)

# 4 * -1
since = time.time()
HAYSTACK4 = copy.deepcopy(HAYSTACK)
HAYSTACK4 = list(map( lambda x : x * -1 ,HAYSTACK4   ))
HAYSTACK4 = insort(HAYSTACK4,NEEDLES)
HAYSTACK4 = list(map( lambda x : x * -1 ,HAYSTACK4   ))
elapsed = time.time() - since
print("Case 4) use multiplying -1 : " , elapsed)

Case 1) use .sort() :  7.159481525421143
Case 2) use sorted() :  7.566699266433716
Case 3) use [::-1] :  7.359405517578125
Case 4) use multiplying -1 :  3.8304331302642822


In [80]:
def grade( score, breakpoints = [60,70,80,90], grades = "FDCBA"):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

print([ grade(score) for score in [33,99,77,70,89,90,100] ])

['F', 'A', 'C', 'C', 'B', 'A', 'A']


## 2.8.2 bisect.insort() 로 삽입하기
- insort(seq, item) 은 seq를 오름차순으로 유지한 채로 item 을 seq를 삽입한다.

In [81]:
import bisect
import random

SIZE = 7
random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' %new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


# 2.9 리스트가 답이 아닐 때
- 배열은 float 객체 대신 바이트 값만 저장하기 때문에 대량의 실수를 저장해야할 때 리스트보다 배열이 효율적이다.
- 리스트의 양쪽 끝에 항목을 계속 추가하거나 삭제하면서 FIFO 나 LIFO 데이터 구조를 구현할 때는 deque(양쪽사용하는 큐)가 더 빠르다.

## 2.9.1 배열
- 시퀀스 안에 숫자만 들어있다면 배열이 리스트보다 훨씬 더 효율적이다.
- 가변 시퀀스가 제공하는 모든 연산 지원
- frombytes(), tofile() 메서드 제공하여 빠르게 파일에 저장하고 읽기 가능

In [82]:
from array import array
from random import random
floats = array('d',(random() for i in range(10**7) ))
print(floats[-1])

0.5963321947530882


In [83]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

In [84]:
floats2 = array('d')
fp = open('floats.bin','rb')
floats2.fromfile(fp,10**7)
fp.close()
print(floats2[-1])

0.5963321947530882


In [85]:
print(floats == floats2)

True


#### 엔디언 변환
- 엔디언(Endianness) : 배열에 바이트 데이터를 넣을 때 바이트 순서를 의미
- 대표적인 엔디안의 종류로 little endian, big endian 이 있다. 윈도우나 인텔 기반의 리눅스는 little endian 방식으로 구동된다. 네트워크상으로 데이터를 전송할 때는 빅 엔디안 기준으로 송수신 된다.
    - big endian : 메모리 공간의 시작 주소에서 메모리 마지막 주소 순서로 쓰는 방식
    - little endian : 메모리 공간의 마지막 주소에서 메모리 시작 주소 순서로 쓰는 방식
- 네트워크로 데이터를 전송할 때 같은 엔디안 시스템을 사용하는 컴퓨터에서는 호환성 문제가 생기지 않으나, 서로 다른 엔디안을 사용하는 컴퓨터의 경우 컴퓨터가 데이터를 제대로 읽지 못하는 경우가 생길 수 있다. 이때문에 바이트의 정렬 방법을 변환해야하는데 이를 엔디언 변환이라고 한다.

https://zion830.tistory.com/38  <br>
https://zion830.tistory.com/39  <br>
https://cypsw.tistory.com/entry/Endian-%EB%B3%80%ED%99%98-%EA%B3%BC%EC%A0%95%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC

## 2.9.2 메모리뷰
- 메모리뷰(memoryview) 내장 클래스는 <b>공유 메모리</b> 시퀀스형으로서 bytes 를 복사하지 않고 배열의 슬라이스를 다룰 수 있게 해준다.
- 공유 메모리(shared memory) : 프로세스에서 메모리는 해당 프로세스만이 사용하는 것이 일반적. 메모리에는 명령어, 지역 변수, 동적 변수, 전역 변수와 같이 데이터가 존재하는데 그 프로세스만이 접근할 수 있고 변경 가능. 일반적으로 이런데 데이터를 다른 프로세스에 쓰일 수 있도록 만들 수 있음. 그것이 공유 메모리라는 IPC ( Inter process communication ) 기법
- 메모리 뷰는 본질적으로 파이썬 자체에 들어있는 NumPy 배열 구조체를 일반화한 것

In [109]:
import array
numbers = array.array('h',[-2,-1,0,1,2])
memv = memoryview(numbers)
print(len(memv))
print(memv[0])

5
-2


In [110]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [111]:
memv_oct[5]=4

## 2.9.3 Numpy와 Scipy

In [118]:
import numpy as np
a = np.arange(12)
print(a)
print(type(a))
print(a.shape)
a.shape = 3,4 # np.reshape 말고 이렇게도 이용할 수가 있네?
print(a)
print(a[2])
print(a[2,1])
print(a[:,1])
print(a.transpose()) # == a.T
print(a.T)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
9
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [124]:
import numpy as np
# 이 전에 floats-10M-lines.txt file 을 만든 기억이 없어서 새로 생성
#floats_10M_lines = np.random.rand(10000000)
#np.savetxt('floats-10M-lines.txt', floats_10M_lines)
# np.save('floats-10M-lines.npy', floats_10M_lines) 로 동일한 배열을 npy 로 만드니까 용량이 1/4 수준

In [126]:
floats = np.loadtxt('floats-10M-lines.txt')

In [127]:
print(floats[-3:])
floats *= .5
print(floats[-3:])

[0.2875971  0.12960808 0.88956701]
[0.14379855 0.06480404 0.44478351]


In [128]:
from time import perf_counter as pc
t0 = pc(); floats /= 3; print(pc() - t0) # 이렇게 하니까 한 줄로 코드 수행하는데 걸리는 시간을 알 수 있네

0.015058400000270922


In [131]:
np.save('floats-10M.npy',floats)
floats2 = np.load('floats-10M.npy','r+')
floats2 *= 6
print(floats2[-3:])

[0.2875971  0.12960808 0.88956701]


## 2.9.4 덱 및 기타 큐
- 리스트의 append() 와 pop() 을 통해 스택이나 큐로 이용할 수 있지만 0번 index 에 삽입, 삭제 연산은 전체 리스트를 이동시켜야 하므로 처리 부담이 크다.
- 덱 ( collections.deque) class 는 큐의 양쪽 어디에서든 빠르게 삽입 및 삭제할 수 있도록 설계된 스레드 안전한 양방향 큐
- 덱은 최대 길이를 설정해서 제한된 항목만 유지

In [138]:
from collections import deque
dq = deque(range(10), maxlen = 10)
print(dq)
dq.rotate(3)
print(dq)
dq.rotate(-4)
print(dq)
dq.appendleft(-1)
print(dq)
dq.extend([11,22,33])
print(dq)
dq.extendleft([10,20,30,40])
print(dq)

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)
deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)


#### 리스트와 덱의 메서드
- 덱은 리스트 메서드 대부분 구현
- popleft() rotate() 처럼 고유한 메서드 존재
- append() 와 popleft() 메서드는 원자성 갖고 있음 ==> 멀티스레드 앱에서 락을 사용하지 않고 덱을 이용해서 간단히 FIFO 큐 구현 가능
    - 원자성(Atomicity) : 트랜잭션(논리적인 작업단위, 장애 발생시 복구 작업이나 병행 제어 작업을 위한 중요한 단위로 사용)의 연산들이 모두 정상적으로 실행되거나 하나도 실행되지 않아햐나는 all or nothing 방식
- 덱의 중간 항목을 삭제하는 연산은 빠르지 않음. 덱이 양쪽 끝에 추가나 제거하는 연산에 최적화되어있기 때문
    - 이러한 이유로 덱에서는 index() 와 insert() 메서드가 없는 것 같음