###### 2.2 지능형 리스트와 제너레이터 표현식

In [4]:
symbols = '!@#$%'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))

In [5]:
codes

[33, 64, 35, 36, 37]

In [3]:
symbols = '!@#$%'
codes = [ord(symbol) for symbol in symbols]
codes

[33, 64, 35, 36, 37]

In [7]:
x = 'ABC'
dummy = [ord(x) for x in x]

In [8]:
x

'ABC'

In [9]:
dummy

[65, 66, 67]

In [11]:
symbols = '!@#$%'
beyond_ascii = [ord(symbol) for symbol in symbols if ord(symbol) > 34]
beyond_ascii

[64, 35, 36, 37]

In [12]:
beyond_ascii = list(filter(lambda c : c > 34, map(ord, symbols)))
beyond_ascii

[64, 35, 36, 37]

In [13]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

In [14]:
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [15]:
for color in colors:
    for size in sizes:
        print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [16]:
tshirts = [(color, size) for size in sizes for color in colors]

In [17]:
tshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

###### 2.3 튜플은 단순한 불변 리스트가 아니다

In [19]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA' , 'CE342567'), ('ESP' , 'XDA205856')]

In [21]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [22]:
print(divmod(20,8))
t = (20,8)
print(divmod(*t))

quotient, remainder = divmod(*t)
print(quotient, remainder)

(2, 4)
(2, 4)
2 4


In [23]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
print(filename)

idrsa.pub


In [24]:
a,b,*rest = range(5)
print(a,b,rest)

0 1 [2, 3, 4]


In [25]:
a,b,*rest = range(3)
print(a,b,rest)

0 1 [2]


In [26]:
a,b,*rest = range(2)
print(a,b,rest)

0 1 []


In [27]:
from collections import namedtuple
City = namedtuple('City','name country population coordinates')
tokyo = City('Tokyo','JP',36.933 , (35.689722,139.691667))
print(tokyo)
print(tokyo.population)
print(tokyo.coordinates)
print(tokyo[1])

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))
36.933
(35.689722, 139.691667)
JP


###### 2.4 슬라이싱

In [28]:
l = [10,20,30,40,50,60]
print(l[:2])
print(l[2:])
print(l[:3])
print(l[3:])

[10, 20]
[30, 40, 50, 60]
[10, 20, 30]
[40, 50, 60]


In [29]:
s = 'bicycle'
print(s[::3])
print(s[::-1])
print(s[::-2])

bye
elcycib
eccb


In [30]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
l[2:5] = [20,30]
print(l)

[0, 1, 20, 30, 5, 6, 7, 8, 9]


In [32]:
del l[5:7]
print(l)

[0, 1, 20, 30, 5, 8, 9]


In [33]:
l[3::2] = [11,22]
print(l)

[0, 1, 20, 11, 5, 22, 9]


In [35]:
l[2:5] = 100

TypeError: can only assign an iterable

######  2.5 시퀀스에 덧셈과 곱셈 연산자 사용하기

In [36]:
l = [1,2,3]
l*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [37]:
5*'abcd'

'abcdabcdabcdabcdabcd'

In [38]:
board = [['_'] *3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [39]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [40]:
weird_board = [['_'] * 3] *3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [42]:
weird_board[1][2] = '0'

In [43]:
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

###### 2.6 시퀀스의 복합 할당

In [44]:
l = [1,2,3]
id(l)

1723998735688

In [45]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [46]:
id(l)

1723998735688

In [48]:
t = (1,2,3)
print(id(t))
t *= 2
print(id(t))

1723998859408
1723997631976


In [50]:
t = (1,2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [51]:
t

(1, 2, [30, 40, 50, 60])

###### 2.7 list.sort()와 sorted() 내장 함수

In [52]:
fruits = ['grape', 'raspberry', 'apple', 'banana']

In [53]:
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [54]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [55]:
sorted(fruits, reverse = True)

['raspberry', 'grape', 'banana', 'apple']

In [56]:
sorted(fruits, key = len, reverse = True)

['raspberry', 'banana', 'grape', 'apple']

In [58]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [59]:
fruits.sort()

In [60]:
fruits

['apple', 'banana', 'grape', 'raspberry']

###### 2.8 정렬된 시퀀스를 bisect로 관리하기

In [63]:
import bisect
import sys

HAYSTACK = [1,4,5,6,8,12,15,20,21,23,23,26,29,30]
NEEDLES = [0,1,2,5,8,10,22,23,29,30,31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        print(ROW_FMT.format(needle, position, offset))
        
if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
        
    else :
        bisect_fn = bisect.bisect
        
    print('DEMO : ', bisect_fn.__name__)
    print('haystack -> ', ' '.join('%2d' %n for n in HAYSTACK))
    demo(bisect_fn)

DEMO :  bisect_right
haystack ->   1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [64]:
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' %new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


###### 리스트가 답이 아닐때

In [74]:
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))

In [75]:
floats[-1]

0.1288579230853678

In [76]:
fp = open('floats.bin', 'wb')

In [77]:
floats.tofile(fp)

In [78]:
fp.close()

In [79]:
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()

In [80]:
floats2[-1]

0.1288579230853678

In [81]:
floats2 == floats

True

In [82]:
import array
numbers = array.array('h', [-2, -1, 0, 1,2])
memv = memoryview(numbers)
len(memv)

5

In [83]:
memv_oct = memv.cast('B')
memv_oct.tolist()
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [84]:
import numpy
a  = numpy.arange(12)
print(a)
print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [86]:
print(a.shape)
a.shape = 3,4
print(a[2])

(12,)
[ 8  9 10 11]


In [87]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [90]:
import numpy
floats = numpy.loadtxt('floats-10M-lines.txt')
floats[-3:]

OSError: floats-10M-lines.txt not found.

In [91]:
from collections import deque
dq = deque(range(10), maxlen = 10)

In [92]:
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
dq.rotate(3)

In [94]:
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [95]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [96]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
dq.extend([11,22,33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [98]:
dq.extendleft([10,20,30,40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])